name: Java CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Compile Java code
      run: |
        javac -d bin src/main/java/Dangnhap/UserRegistrationTestNG.java  # Thay đổi đường dẫn nếu cần

    - name: Run tests
      run: |
        java -cp bin org.junit.runner.JUnitCore UserRegistrationTestNG.java  # Thay đổi với tên lớp test của bạn
